### ISSUE TITLE
Compatibility with PDS4 version 1.13.0.0

### ISSUE THREAD

**Issue by LandingEllipse** [NASA-PDS/PLAID#2]
Hi there,

I've just taken PLAID for a spin at it seems to be a really nifty tool. However, I am wondering whether there are plans to update PLAID to support v1.13 of the information model? If not, could you provide a rough estimate of the work required to complete such work?

All the best,
Ariel Ladegaard

**Comment by stirlingalgermissen** [comment]
Hi Ariel,

We plan on supporting this version – I will get you a timeframe when I have it. Glad to hear the tool is working out for you.

Thanks,
Stirling

**Comment by jordanpadams** [comment]
@stirlingalgermissen checking in what the status is here?

**Comment by jordanpadams** [comment]
duplicate of #15. working to get this deployed in the next few weeks
