### ISSUE TITLE
Revise Docker and deployment docs for open source access

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PLAID#30]
## 📖 Additional Details

* See PR here for initial version of docs: https://github.com/NASA-PDS/PLAID/pull/29
* Per [this comment](https://github.com/NASA-PDS/PLAID/pull/29#issuecomment-932635296), we need to update the Docker deployment and procedures to use publicly available images

## ⚖️ Acceptance Criteria
**Given** a desire to deploy PLAID
**When I perform** the procedure described here (link TBD) to deploy using docker containers for dev purposes
**Then I expect** to be able to spin up PLAID and run in a dev environment

**Given** a desire to deploy PLAID
**When I perform** the procedure described here (link TBD) to deploy using docker containers for ops purposes (includes instructions for necessary HTTP proxying, file system mounting, etc)
**Then I expect** to be able to spin up PLAID and run in a dev environment

**Comment by jordanpadams** [comment]
@nutjob4life ☝️

**Comment by jordanpadams** [comment]
@nutjob4life feel free to blow up the README/docs however you see fit. We can continue to use the README, or we can setup Sphinx docs as well if that makes sense. Whatever you think is best.

**Comment by nutjob4life** [comment]
Thanks to `log4j` vulnerabilities I'm finally getting to this today. However there are some architectural things I think we should tackle in addition to documentation, the big one being sending email (password registration, etc.). The system is hard-coded right now to use JPL's SMTP server, which works fine if you have JPL VPN but if you're any old open-source developer off the street, you basically can't run this on your desktop.

I can do "just the docs" but I'd like to go a step further and clean up the SMTP configuration, parameterize the `docker-compose`, clean up the `Dockerfile`, etc., that it's more like other open-source containers. That's the approach I'm taking right now, so stop me by commenting on this ticket before I go too far 😝

**Comment by jordanpadams** [comment]
@nutjob4life sounds great! Whatever you think makes sense. Do you mind updating the estimate for the ticket?

**Comment by nutjob4life** [comment]
@jordanpadams gonna maybe bump this up a little bit more. I've gotten the sendmail issue solved but the next thing that's bugging me is that the Docker image actually contains _no code_ 😦 It's a base PHP image + a custom `docker-entrypoint.sh` and that's it.

If you were grabbing this image off `hub.docker.com` and expecting it to do something, you'd be sorely disappointed.  The only way it works is if you happen to have the `PLAID` source layout in the current directory and map the volume `/var/www/html` to `${PWD}`.

This is _not_ a containerized app! 😑

But given it's the long holiday weekend, I'd like to see if I can remedy that too and make the image truly self-contained. You _shouldn't_ need to pull the image _and_ clone the repo! 😅

**Comment by jordanpadams** [comment]
thanks for the clarification @nutjob4life ! sounds good. i appreciate the approach here since we don't want to have to re-containerize this app in the future the right way :-)
