### ISSUE TITLE
Base image used by APPS PLAID is not supported

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/PLAID#32]
## Vulnerability

"APPS PLAID" uses as its base Docker image `php:5.6-apache-jessie`.

Debian Linux `jessie` reached end-of-life on 2018-06-17 and end of long-term support on 2020-06-30. It has received no security updates since then.

PHP 5.6 reached end of life on 2019-01-01 and has no long-term support. It has received no security updates since then.

Upgrading the base image of "APPS PLAID" is strenuously recommended.

## Software Version
`main`

**Comment by jordanpadams** [comment]
@nutjob4life how critical do you think this is? should we do this now? would it introduce a security vulnerability to move forward without this upgrade?

**Comment by nutjob4life** [comment]
I think this is pretty high priority. PHP 8.1.0–8.1.1, PHP 7.4.26–7.4.27, and PHP 7.3.3 are considered "safe" (at least as far as "safe" goes for something as horrible as PHP).

All PHP < 7 has CVSS scores of 8.2 to 10.0 (extremely unsafe). See [this chart](https://maikuolan.github.io/Vulnerability-Charts/php.html) for details.

The Linux distribution being out-of-date is not as pressing—but is easier to fix.

**Comment by gxtchen** [comment]
@tloubrieu-jpl @jordanpadams @viviant100 Can you provide a scan report, personal docker account does not support Vulnerability scanning.

**Comment by jordanpadams** [comment]
@gxtchen are you sure? from this image on the top of the page, looks like everyone should get 10 image scans:

<img width="971" alt="Screen Shot 2022-04-18 at 8 15 00 AM" src="https://user-images.githubusercontent.com/33492486/163829776-c06eb7e0-899d-4c09-a737-7b83ab20a994.png">

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen ,

I created an account on https://snyk.io/ (using my github credentials).

Then in the command line:

docker scan --login
docker scan plaid

Then I had this report (which does not look perfect...)

[snyk_scan_plaid_report.txt.zip](https://github.com/NASA-PDS/PLAID/files/8506886/snyk_scan_plaid_report.txt.zip)
