### ISSUE TITLE
As a PDS Operator, I want to update PLAID to the latest PDS4 Discipline PDS Data Dictionaries

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PLAID#4]
https://pds.nasa.gov/datastandards/dictionaries/

| Namespace | Parent Class |
| ------------ | ---------------- |
proc | proc:Processing_Information
sp | sp:Spectral_Characteristics
img_surface | img_surface:Surface_Imaging
nucspec | nucspec:NucSpec_Observation_Properties
msn | msn:Mission_Information
img | img:Imaging
geom | geom:Geometry
speclib | speclib:Spectral_Library_Product
msss_cam_mh | msss_cam_mh:MSSS_Camera_Mini_Header
disp | disp:Display_Settings
cart | cart:Cartography
msn_surface | msn_surface:Surface_Mission_Information
rings | rings:Ring_Moon_Systems
survey | survey:Survey

**Comment by jordanpadams** [comment]
@jeffyuhaoliu here is a JSON with all discipline LDDs and the PDS Core namespace.


[PDS4_ALL_1F00.JSON.zip](https://github.com/NASA-PDS/PLAID/files/5838718/PDS4_ALL_1F00.JSON.zip)

**Comment by voxparcxls** [comment]
@jordanpadams PDS4 1F00 data dict JSON is added and in the PLAID schema version options

**Comment by jordanpadams** [comment]
closed per #22
